baseURL = "https://blog.pmatarodrigues.com"
languageCode = "en-us"
title = "pmatarodrigues $ blog"
theme = "novela"

# Novela settings

paginate = 6

[social]
twitter= "https://twitter.com/pmatarodrigues"
github= "https://github.com/pmatarodrigues"
linkedin= "https://www.linkedin.com/in/pmatarodrigues"

[taxonomies]
author = "authors"
